KOMODO_DB_USERNAME="{{ op://kdk-cluster/komodo-db/username }}"
KOMODO_DB_PASSWORD="{{ op://kdk-cluster/komodo-db/password }}"
KOMODO_PASSKEY="{{ op://kdk-cluster/komodo-passkey/credential }}"
KOMODO_JWT_SECRET="{{ op://kdk-cluster/komodo-jwt-secret/credential }}"
KOMODO_WEBHOOK_SECRET="{{ op://kdk-cluster/komodo-webhook-secret/credential }}"
KOMODO_ADMIN_USERNAME="{{ op://kdk-cluster/komodo-admin/username }}"
KOMODO_ADMIN_PASSWORD="{{ op://kdk-cluster/komodo-admin/password }}"
